# Databricks notebook source
# MAGIC %md
# MAGIC # Task 4: Lever Loop — Training Guide
# MAGIC
# MAGIC | Quick Reference | |
# MAGIC |---|---|
# MAGIC | **Task** | 4 of 6 — Lever Loop (Adaptive Optimization Engine) |
# MAGIC | **Harness functions** | `_run_lever_loop()` in `optimization/harness.py` |
# MAGIC | **Reads from** | `preflight` (run context, levers, max_iterations) + `baseline_eval` (scores, overall_accuracy, thresholds_met, model_id) + `enrichment` (enrichment_model_id, enrichment_skipped, **plus** Tier 1.3 post-enrichment values: `post_enrichment_accuracy`, `post_enrichment_scores`, `post_enrichment_model_id`, `post_enrichment_thresholds_met`) |
# MAGIC | **Publishes to** | `finalize` (scores, accuracy, model_id, iteration_counter, debug_info) |
# MAGIC
# MAGIC > **📝 Note:** When `post_enrichment_*` is present, `prev_accuracy` / `prev_scores` / `thresholds_met` are sourced from there (logged as `prev_accuracy_source="enrichment.post_enrichment_accuracy"`); otherwise the loop falls back to `baseline_eval` (`prev_accuracy_source="baseline_eval"`). This closes the ghost-ceiling regression loop where the loop gated against a stale baseline while clustering read post-enrichment rows (Tier 1.3).
# MAGIC | **Typical duration** | 15–90 min (depends on iteration count and benchmark size) |
# MAGIC | **Log label** | `[TASK-4 LEVER_LOOP]` |
# MAGIC
# MAGIC ## 🎯 Purpose
# MAGIC
# MAGIC Task 4 is the **adaptive optimization engine** of the Genie Space Optimizer. Proactive enrichment has already been applied by Task 3. Each iteration it re-diagnoses failures from the latest evaluation, re-strategizes by generating a single targeted action group, applies patches through a 3-gate pattern, and reflects on the outcome to guide the next iteration.
# MAGIC
# MAGIC ## 🏗️ DAG Position
# MAGIC
# MAGIC | Step | Task | Status | Reads From | Publishes To |
# MAGIC |:----:|------|:------:|------------|--------------|
# MAGIC | 1 | preflight | Done | widgets | all tasks |
# MAGIC | 2 | baseline_eval | Done | preflight | enrichment |
# MAGIC | 3 | enrichment | Done | preflight + baseline | lever_loop |
# MAGIC | 4 | **lever_loop** | **⬅️ THIS TASK** | preflight + baseline + enrichment | finalize |
# MAGIC | 5 | finalize | Next | lever_loop | deploy |
# MAGIC | 6 | deploy | Pending | preflight + finalize | *(terminal)* |
# MAGIC
# MAGIC > **📝 Note:** This task runs only when baseline does *not* meet thresholds (`run_if: !thresholds_met`). An internal baseline gate provides a safety check even if the job configuration allows the task to run.
# MAGIC
# MAGIC ## The 5 Lever Categories
# MAGIC
# MAGIC Patches generated by the adaptive strategist draw from 5 lever categories. The strategist decides which levers to use per iteration based on the current failure landscape — they are **not** iterated sequentially.
# MAGIC
# MAGIC | Lever | Name | What It Optimizes | Example Patches | Risk |
# MAGIC |:-----:|------|-------------------|-----------------|:----:|
# MAGIC | 1 | **Tables & Columns** | Column descriptions, aliases, synonyms | `update_column_description`, `add_column_synonym` | 🔵 Low–Med |
# MAGIC | 2 | **Metric Views** | MV measures, dimensions, YAML definitions | `update_mv_measure`, `add_mv_dimension`, `update_mv_yaml` | 🟠 Med–High |
# MAGIC | 3 | **Table-Valued Functions** | TVF SQL, parameters, signatures | `update_tvf_sql`, `add_tvf_parameter`, `add_tvf` | 🟠 Med–High |
# MAGIC | 4 | **Join Specifications** | Table relationships, join columns (reactive + column-name discovery) | `add_join_spec`, `update_join_spec`, `remove_join_spec` | 🔵 Medium |
# MAGIC | 5 | **Genie Space Instructions** | Routing rules, disambiguation, default behaviors, example SQL queries | `add_example_sql`, `update_example_sql`, `add_instruction`, `update_instruction` | 🔵 Low–Med |
# MAGIC
# MAGIC > **📝 Note:** Lever 5 priority hierarchy: SQL expressions > example SQL > text instructions. Most Lever 5 failures are routed to `add_example_sql` (preferred), with text instructions used only as a last resort. A **100-instruction slot budget** is enforced (see Instruction Slot Budget section below).
# MAGIC
# MAGIC > **📝 Note:** Format assistance and entity matching are applied automatically between baseline and the lever loop (Stage 2.5). Levers 1–3 are governed by `apply_mode` (genie_config, uc_artifact, or both). Levers 4–5 always write to Genie Space config.
# MAGIC
# MAGIC ## Convergence Logic
# MAGIC
# MAGIC The adaptive loop exits when any of these conditions is met:
# MAGIC - **All thresholds met** — every judge (e.g. syntax_validity, schema_accuracy) meets its target
# MAGIC - **Diminishing returns** — the last N accepted iterations each improved accuracy by less than epsilon (default 2.0%)
# MAGIC - **No actionable clusters** — no remaining failure clusters to address (all fixed or all previously attempted)
# MAGIC - **Strategist produces 0 action groups** — the LLM determines there is nothing left to fix
# MAGIC - **Max iterations reached** — `iteration_counter >= max_iterations`
# MAGIC - **Arbiter-saturated, no clusters** (Tier 1.6) — baseline accuracy ≥ 99% AND zero unified hard failures: tagged `convergence_reason="arbiter_saturated_no_clusters"` and exits without firing the loop. Distinct from `arbiter_saturated` (kept for cases where arbiter mostly overrode but unified hard failures remain).

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔧 Architecture: Adaptive Iteration Cycle
# MAGIC
# MAGIC The lever loop uses an **adaptive iteration cycle**. Each iteration re-diagnoses, re-strategizes, applies, evaluates, and reflects:
# MAGIC
# MAGIC ```
# MAGIC for iteration in 1..max_iterations:
# MAGIC     re-cluster failures → score by impact → strategist (1 AG) →
# MAGIC     apply patches → 3-gate eval → accept/rollback → reflect
# MAGIC ```
# MAGIC
# MAGIC | Step | What Happens | Key Function |
# MAGIC |:----:|--------------|-------------|
# MAGIC | 1 | **Re-cluster** failures from the latest **non-rolled-back** full iteration (baseline on iter 1, last accepted eval on iter 2+) using the unified `row_is_hard_failure` predicate (Tier 1.4) | `_analyze_and_distribute()` |
# MAGIC | 2 | **Filter** clusters already attempted via `tried_patches` | `_filter_tried_clusters()` |
# MAGIC | 3 | **Rank** clusters by impact score (causal weight, severity, fixability) | `rank_clusters()` |
# MAGIC | 4 | **Strategist** call: 1 LLM call with reflection buffer and priority ranking produces exactly 1 action group | `_call_llm_for_adaptive_strategy()` |
# MAGIC | 5 | **Generate** proposals and **apply** patches | `generate_proposals_from_strategy()` + `apply_patch_set()` |
# MAGIC | 6 | **3-gate eval**: slice → P0 → full | `_run_gate_checks()` |
# MAGIC | 7 | **Accept or rollback** based on gate results | `rollback()` on failure |
# MAGIC | 8 | **Reflect**: build reflection entry, update `tried_patches` | `_build_reflection_entry()` |
# MAGIC
# MAGIC ### 3-Gate Pattern
# MAGIC
# MAGIC For each iteration, after patches are applied, the harness runs **three evaluation gates** in sequence:
# MAGIC
# MAGIC | Gate | Scope | Pass Condition | On Failure |
# MAGIC |:----:|-------|---------------|------------|
# MAGIC | **1. Slice** | Only benchmarks touching **patched objects** | No regression vs. best scores (noise-floor-adjusted `SLICE_GATE_TOLERANCE`). **Tier 3.12:** small corpora (≤30 benchmarks) use a relaxed `_slice_threshold = 0.9` so the gate stays useful when affected_qids covers most of the suite. | Rollback → reflect → next iteration |
# MAGIC | **2. P0** | Top 3 most critical questions | Zero P0 failures | Rollback → reflect → next iteration |
# MAGIC | **3. Full** | All benchmarks | No regression vs. best scores (noise-floor-adjusted `REGRESSION_THRESHOLD`). **Tier 1.5:** `overall_accuracy_guard` triggers only when `full_accuracy < best_accuracy − noise_floor`, not on any drop. **Tier 1.8:** `result_correctness` regressions are suppressed when `both_correct_rate` held within tolerance — that is hash-noise (column reorder, alias rename), not a semantic regression. | Rollback → reflect → next iteration |
# MAGIC
# MAGIC **On full-gate success:** Accept iteration → update best_scores/best_model_id → write iteration to Delta → register instruction version snapshot → update reference SQLs → log expectations on traces.
# MAGIC
# MAGIC ### Reflection Buffer
# MAGIC
# MAGIC Each iteration produces a **reflection entry** recording what was attempted, whether it was accepted or rolled back, the score delta, which levers and targets were involved, and lessons learned. The strategist receives recent reflections in full detail and older ones in compressed form. A **"DO NOT RETRY" list** prevents the strategist from repeating previously failed approaches.
# MAGIC
# MAGIC ### AG Scope: One Source Cluster Per AG (Tier 2.5)
# MAGIC
# MAGIC The strategist prompt enforces **one source cluster per AG**. A post-LLM validator inspects `source_cluster_ids`: if the LLM returned multiple clusters with **different** `root_cause` values, the validator drops all but the highest-`cluster_impact` cluster and back-fills `affected_questions` from that cluster's `base_question_ids` (Tier 2.1). Multi-cluster failure patterns are addressed across multiple iterations rather than one giant AG that risks taking down the other 26 patches when one bad patch rolls back.
# MAGIC
# MAGIC ### Cluster-Level Impact Scoring
# MAGIC
# MAGIC Failure clusters are scored deterministically as `q_count × causal_weight × severity × fixability × soft_dampen` (see `cluster_impact` in `optimization/optimizer.py`). Higher-impact clusters are addressed first.
# MAGIC
# MAGIC **Tier 2.3 — Soft-cluster ranking.** Soft clusters (rows where the arbiter said the result was correct but individual judges flagged suboptimal patterns) are dampened by `0.5` so hard clusters dominate at equal `q_count`, while a large soft cluster (e.g. a 12-question `response_quality=63%` block) can still out-rank a tiny hard cluster and earn strategist attention.
# MAGIC
# MAGIC **Tier 2.11 — Unified qid state across hard + soft.** Hard and soft clustering passes share a single `qid_state` dict so a physical row that fails both pathways gets one stable qid (with `:vN` suffix on signature collisions) and lands in exactly one cluster with one dominant root cause. Without this, Q001 could appear as `missing_aggregation` in the hard cluster and `wrong_filter_condition` in the soft cluster — the DO-NOT-RETRY bookkeeping then can't reconcile them.
# MAGIC
# MAGIC **Tier 2.12 — `base_question_id` propagated separately.** Each profile carries `base_question_id` (the real benchmark id) and `trial_index` so `:vN` tokens never leak into outward-facing fields: `ag.affected_questions`, provenance rows, slice-gate samples, UI drill-down, human-review flagging. Internal dedup keys stay `(base_question_id, trial_index)`.
# MAGIC
# MAGIC **Tier 2.15 — Counterfactual merge across signal types.** A cluster's `asi_counterfactual_fixes` is computed across hard+soft pathway profiles for the same `base_question_id`. The SQL-shape suppression (drop NL_TEXT/META counterfactuals on SQL-shape clusters) runs **after** the merge, so a cluster never shows `Counterfactual: (none)` when a sibling pathway has actionable fixes.
# MAGIC
# MAGIC ### Rollback Mechanism
# MAGIC
# MAGIC When any gate fails, `rollback(apply_log, w, space_id, metadata_snapshot)` reverses all applied patches. The space returns to its pre-iteration state. Patches are marked as rolled back in Delta for audit.
# MAGIC
# MAGIC > **📝 Note:** Tier 1.1 / 1.2 — `mark_patches_rolled_back` stamps **both** the `genie_opt_patches` rows **and** the `genie_opt_iterations` row with `rolled_back=true`, `rolled_back_at`, and `rollback_reason`. Every "current state" reader filters rolled-back rows by default: `load_latest_full_iteration` (clustering input), `_get_baseline_and_best_accuracy` (UI optimizedScore), and `promote_best_model` (champion selection). Iteration 0 is always retained as the floor of the max aggregation. Without this stamp, iteration N+1's clustering would re-read iteration N's rolled-back rows — the ghost-cluster feedback loop.
# MAGIC
# MAGIC ### Instruction Slot Budget
# MAGIC
# MAGIC The Genie API enforces a hard limit of **100 instruction slots** (each example SQL = 1, each SQL function = 1, the entire text instructions block = 1). The optimizer enforces this at three levels:
# MAGIC - **Proposal validation**: `_validate_lever5_proposals()` caps `add_example_sql` proposals at remaining budget
# MAGIC - **Post-apply guard**: `apply_patch_set()` trims excess examples if the limit is somehow breached
# MAGIC - **Structural validation**: `_strict_validate()` rejects any config exceeding 100 slots before it reaches the API
# MAGIC
# MAGIC ### Patch Cap & Applier Gates (Tier 2.6 / 2.8 / 2.10)
# MAGIC
# MAGIC | Gate | Where | What it does |
# MAGIC |---|---|---|
# MAGIC | `MAX_AG_PATCHES = 8` | `common/config.py`, enforced in `_run_lever_loop` before `apply_patch_set` | Bounds rollback blast radius — one bad patch in a 27-patch AG used to take down the other 26 (Tier 2.6). Excess tail patches are dropped with a warning; remaining targets are addressed in subsequent iterations. |
# MAGIC | `validation_passed` required for `add_sql_snippet_*` | `optimization/applier.py::render_patch` | Refuses to apply any `add_sql_snippet_*` patch without `validation_passed=True` from `validate_sql_snippet` (Tier 2.8). Closes the bug where `CAST_INVALID_INPUT` validation failures were logged but the snippet still landed via a different code path. |
# MAGIC | `rewrite_instruction` defaults to a CONSTRAINTS section merge | `optimization/applier.py::render_patch` | Full PURPOSE-through-everything rewrites (Tier 2.10) require explicit `escalation="full_rewrite"` (or `GSO_ALLOW_UNSCOPED_REWRITE=1`). The default behaviour converts the patch to a `update_section` against `CONSTRAINTS` so collateral-damage rewrites don't strand 5+ unrelated questions per iteration. |
# MAGIC
# MAGIC ### Section Routing (Tier 2.7)
# MAGIC
# MAGIC When Lever 5's strategist returns instruction-section content for sections it doesn't own (per `LEVER_TO_SECTIONS`), `generate_proposals_from_strategy` checks whether **another invoked lever in the same AG** owns that section:
# MAGIC
# MAGIC - If yes — re-route the section to that lever via `action_group["_pending_section_routing"]`. The owning lever's proposal generator picks it up in the same iteration.
# MAGIC - If no — drop the section. Don't fold into CONSTRAINTS (which historically polluted Lever 5 prose with `JOIN GUIDANCE` and `TEMPORAL FILTERS` content owned by Levers 4 and 2).
# MAGIC
# MAGIC ### Instruction-Only Fallback (Tier 2.9)
# MAGIC
# MAGIC > **📝 Note:** When `cluster_driven_synthesis` declines, `optimization/synthesis.py::instruction_only_fallback` returns a proposal **only if** the AFS carries an actionable `counterfactual_fixes` entry of ≥20 chars. Bare metadata like `Failure type: missing_aggregation` is never written into Genie Space `text_instructions` — it polluted every subsequent prompt the space saw and is now suppressed at the source.
# MAGIC
# MAGIC ### Arbiter Benchmark Corrections (Pre-Loop)
# MAGIC
# MAGIC > **📝 Note:** Before the adaptive loop begins, the harness runs `_extract_arbiter_actions_from_baseline()` to find rows where the arbiter verdict was `genie_correct` — meaning Genie's SQL was actually correct and the benchmark's expected SQL was wrong. When `genie_correct` verdicts meet or exceed `ARBITER_CORRECTION_TRIGGER` (default 3), `apply_benchmark_corrections()` rewrites those benchmarks' `expected_sql`. This prevents chasing false failures caused by stale gold SQL.
# MAGIC
# MAGIC ### Unified Hard-Failure Predicate (Tier 1.4)
# MAGIC
# MAGIC During each iteration, `_analyze_and_distribute` partitions rows using the **unified hard-failure predicate** `row_is_hard_failure(row)` from `optimization/evaluation.py`:
# MAGIC
# MAGIC ```
# MAGIC row_is_hard_failure(row) ≡
# MAGIC     result_correctness == "no" AND arbiter NOT IN {both_correct, genie_correct}
# MAGIC ```
# MAGIC
# MAGIC This is the **same** predicate the accept gate uses for accuracy counting. Rows where `rc=yes` AND the arbiter said `ground_truth_correct` (Genie's row set happened to match GT despite semantically wrong SQL) are no longer routed to hard clusters — they remain in the `arbiter_excluded` bucket so the gate's 100% accuracy reading and the clusterer's view of "failures" agree. Before this unification, the loop produced phantom hard clusters even when the gate saw 100% accuracy.
# MAGIC
# MAGIC | Row | rc | arbiter | Hard cluster? | Counted correct? |
# MAGIC |---|---|---|---|---|
# MAGIC | both ok | yes | both_correct | no (arbiter_excluded) | yes |
# MAGIC | rc-yes, GT-correct | yes | ground_truth_correct | **no** (arbiter_excluded — Tier 1.4 fix) | yes (rc=yes override) |
# MAGIC | arbiter override of bad SQL | no | both_correct | no (arbiter_excluded) | yes (arbiter override) |
# MAGIC | genuine hard failure | no | ground_truth_correct | **yes** (filtered_failure_rows) | no |
# MAGIC | judge-only soft failure | yes | both_correct | no (soft_signal_rows if any judge fails) | yes |
# MAGIC
# MAGIC ### Reference SQL Tracking
# MAGIC
# MAGIC The harness extracts `reference_sqls` (question → SQL mapping) from the baseline iteration. These are passed to every evaluation call for cross-iteration SQL consistency tracking. When an iteration is accepted, reference SQLs are updated with new results.
# MAGIC
# MAGIC ### Noise Floor Adjustment for Gate Tolerances
# MAGIC
# MAGIC > **💡 Tip:** To prevent false regression signals on small benchmark sets, the harness computes: `noise_floor = 100.0 / max(len(benchmarks), 1)`. Gate tolerances are adjusted:
# MAGIC > - **Slice gate:** `effective_tolerance = max(SLICE_GATE_TOLERANCE, noise_floor + 2.0)`
# MAGIC > - **Full eval:** `effective_threshold = max(REGRESSION_THRESHOLD, noise_floor)`
# MAGIC >
# MAGIC > Example: 10 benchmarks → noise floor 10.0% → full eval threshold = `max(10.0, 10.0) = 10.0%`, slice gate = `max(15.0, 12.0) = 15.0%`.
# MAGIC
# MAGIC ### SQL Context (USE CATALOG / USE SCHEMA)
# MAGIC
# MAGIC Before each evaluation (slice, P0, full), the harness calls `_ensure_sql_context(spark, catalog, schema)`:
# MAGIC
# MAGIC ```sql
# MAGIC USE CATALOG `{catalog}`;
# MAGIC USE SCHEMA `{schema}`;
# MAGIC ```
# MAGIC
# MAGIC > **⚠️ Warning:** Without this, you may see "target schema not in current catalog" errors when the default session catalog differs from the Genie Space's UC location.
# MAGIC
# MAGIC ### MLflow Labeling Session
# MAGIC
# MAGIC At the end of the loop, a labeling session is created for human review via `create_review_session()`. Traces from evaluation runs are populated into the session, and the session URL is persisted to Delta and surfaced in the UI. Expected SQL is logged on each trace via `mlflow.log_expectation()` so reviewers can see the ground truth alongside generated SQL.
# MAGIC
# MAGIC ### What `thresholds_met` Means
# MAGIC
# MAGIC `thresholds_met` is a boolean originally produced by Task 2 (baseline_eval). It is `True` when `all_thresholds_met(scores, DEFAULT_THRESHOLDS)` returns `True` — i.e., every quality dimension meets its target threshold. When `True`, the lever loop is skipped.
# MAGIC
# MAGIC > **📝 Note:** Tier 1.3 — when Task 3 publishes `post_enrichment_thresholds_met=True`, this notebook prefers it over `baseline_eval.thresholds_met`. Enrichment can flip the bool either direction (sealing thresholds the baseline missed, or revealing post-enrichment regressions); the loop reads the freshest signal so it doesn't run unnecessary iterations or skip warranted ones.
# MAGIC
# MAGIC ### MLflow Run Naming v2 (Tier 4)
# MAGIC
# MAGIC Every MLflow run uses the v2 scheme `<run_short>/<stage>/<detail>` from `common/mlflow_names.py`. Iteration indices are zero-padded so MLflow's lex-sort produces the chronological order:
# MAGIC
# MAGIC | Stage | v2 run name |
# MAGIC |---|---|
# MAGIC | Strategy call | `e9c0b491/iter_03_strategy/AG2` |
# MAGIC | Slice eval | `e9c0b491/iter_03_slice_eval` |
# MAGIC | P0 eval | `e9c0b491/iter_03_p0_eval` |
# MAGIC | Full eval (run 1) | `e9c0b491/iter_03_full_eval/run_1` |
# MAGIC | Full eval (confirm) | `e9c0b491/iter_03_full_eval/run_2_confirm` |
# MAGIC
# MAGIC Every run also carries `genie.run_id`, `genie.iteration` (zero-padded), `genie.stage`, `genie.ag_id`, and `genie.run_name_version="v2"` tags so operators can filter the experiment by tag without parsing names. Retries append `/retry_{k}` rather than minting fresh names.
# MAGIC
# MAGIC ### INFO-Only Judges (Tier 3.6)
# MAGIC
# MAGIC `repeatability` and `previous_sql` are **diagnostic-only** judges (`threshold == 0.0` in `DEFAULT_THRESHOLDS`). Their failures are tracked for observability — every iteration produces fresh SQL that differs from the prior iteration's, and that difference shows up as a "failure" of these two judges — but they are excluded from clustering and soft-signal detection via `INFO_ONLY_JUDGES` in `common/config.py`. Without this exclusion, every row in iteration 2+ would appear in a soft cluster purely because the SQL was newly generated.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🚪 Baseline Gate: Skip If Thresholds Already Met
# MAGIC
# MAGIC > **📝 Note:** Even if this task runs (e.g. due to job configuration), we check `thresholds_met` at the start. If the baseline already meets all quality thresholds, we publish baseline values as-is and exit early — no lever iterations needed.
# MAGIC
# MAGIC On skip:
# MAGIC - Publish baseline scores, accuracy, model_id as the final result
# MAGIC - Set `iteration_counter=0`, `skipped=True`
# MAGIC - Exit with `dbutils.notebook.exit("SKIPPED: baseline meets thresholds")`

# COMMAND ----------

import json
import traceback
from functools import partial
from typing import Any, cast

from databricks.sdk import WorkspaceClient
from pyspark.sql import SparkSession

from genie_space_optimizer.jobs._helpers import _banner as _banner_base
from genie_space_optimizer.jobs._helpers import _log as _log_base
from genie_space_optimizer.optimization.evaluation import load_benchmarks_from_dataset
from genie_space_optimizer.optimization.harness import _run_lever_loop

dbutils = cast(Any, globals().get("dbutils"))

_TASK_LABEL = "TASK-4 LEVER_LOOP"
_banner = partial(_banner_base, _TASK_LABEL)
_log = partial(_log_base, _TASK_LABEL)

# COMMAND ----------

# MAGIC %md
# MAGIC ## ⚙️ Reading Upstream Task Values
# MAGIC
# MAGIC Task 4 reads from three upstream tasks:
# MAGIC
# MAGIC | Source | Keys | Purpose |
# MAGIC |--------|------|---------|
# MAGIC | `preflight` | `run_id`, `space_id`, `domain`, `catalog`, `schema` | Run and UC context |
# MAGIC | `preflight` | `experiment_name` | MLflow experiment for evaluations |
# MAGIC | `preflight` | `max_iterations` | Cap on lever loop iterations |
# MAGIC | `preflight` | `levers` | Lever indices to try (default `[1,2,3,4,5]`) |
# MAGIC | `preflight` | `apply_mode` | Where levers 1–3 write: `genie_config`, `uc_artifact`, or `both` |
# MAGIC | `baseline_eval` | `scores` | Per-judge scores (JSON) |
# MAGIC | `baseline_eval` | `overall_accuracy` | Aggregate accuracy |
# MAGIC | `baseline_eval` | `thresholds_met` | `True` if baseline already meets all quality thresholds |
# MAGIC | `baseline_eval` | `model_id` | Genie model version ID for iteration 0 |
# MAGIC | `enrichment` | `enrichment_model_id` | LoggedModel snapshot of enriched Genie Space |
# MAGIC | `enrichment` | `enrichment_skipped` | Whether enrichment was skipped (baseline met thresholds) |

# COMMAND ----------

from genie_space_optimizer._workspace_client import make_workspace_client
w = make_workspace_client()
spark = SparkSession.builder.getOrCreate()

# Widgets — Databricks Jobs guarantees these survive Repair Run.
dbutils.widgets.text("run_id", "")
dbutils.widgets.text("catalog", "")
dbutils.widgets.text("schema", "")
_widget_run_id = dbutils.widgets.get("run_id").strip()
_widget_catalog = dbutils.widgets.get("catalog").strip()
_widget_schema = dbutils.widgets.get("schema").strip()

from genie_space_optimizer.jobs._handoff import (
    HandoffSource,
    assert_lever_loop_inputs_sane,
    get_baseline_eval_state,
    get_enrichment_state,
    get_run_context,
)

ctx = get_run_context(
    spark,
    run_id_widget=_widget_run_id,
    catalog_widget=_widget_catalog,
    schema_widget=_widget_schema,
    dbutils=dbutils,
)

run_id = ctx["run_id"].value
space_id = ctx["space_id"].value
domain = ctx["domain"].value
catalog = ctx["catalog"].value
schema = ctx["schema"].value
exp_name = ctx["experiment_name"].value
max_iterations = ctx["max_iterations"].value
levers = ctx["levers"].value
apply_mode = ctx["apply_mode"].value
triggered_by = ctx["triggered_by"].value or ""
human_corrections = ctx["human_corrections"].value or []
max_benchmark_count = ctx["max_benchmark_count"].value

import os as _os
_warehouse_id = ctx["warehouse_id"].value or ""
if _warehouse_id:
    _os.environ["GENIE_SPACE_OPTIMIZER_WAREHOUSE_ID"] = _warehouse_id

# Cycle 11 — production defaults to warn-and-degrade for the loop
# invariant suite (typed INVARIANT_VIOLATION records, no AssertionError
# raise). CI / replay can override by setting
# GSO_LOOP_INVARIANTS_STRICT=1 explicitly.
_os.environ.setdefault("GSO_LOOP_INVARIANTS_STRICT", "0")

baseline = get_baseline_eval_state(
    spark, run_id=run_id, catalog=catalog, schema=schema, dbutils=dbutils,
)
_baseline_scores = baseline["scores"].value
_baseline_accuracy = baseline["overall_accuracy"].value
_baseline_thresholds_met = baseline["thresholds_met"].value
baseline_model_id = baseline["model_id"].value

enrichment = get_enrichment_state(
    spark, run_id=run_id, catalog=catalog, schema=schema, dbutils=dbutils,
)
enrichment_model_id = enrichment["enrichment_model_id"].value or ""
enrichment_skipped = enrichment["enrichment_skipped"].value
post_enrichment_accuracy = enrichment["post_enrichment_accuracy"].value
post_enrichment_scores = enrichment["post_enrichment_scores"].value
post_enrichment_model_id = enrichment["post_enrichment_model_id"].value
post_enrichment_thresholds_met = enrichment["post_enrichment_thresholds_met"].value

# Tier 1.3: prefer post-enrichment eval values when present. Enrichment
# mutates the Genie Space, so the baseline scorecard can be arbitrarily
# stale by the time Task 4 starts. Without this, gate checks compare
# against the pre-enrichment baseline while clustering reads post-
# enrichment rows — the mismatch is the cause of the ghost-ceiling
# regression loop.
prev_scores = _baseline_scores
prev_accuracy = _baseline_accuracy
thresholds_met = _baseline_thresholds_met
prev_model_id = baseline_model_id
_accuracy_source = "baseline_eval"

if post_enrichment_accuracy is not None:
    prev_accuracy = post_enrichment_accuracy
    if post_enrichment_scores is not None:
        prev_scores = post_enrichment_scores
    if post_enrichment_model_id:
        prev_model_id = post_enrichment_model_id
    if post_enrichment_thresholds_met is not None:
        thresholds_met = post_enrichment_thresholds_met
    _accuracy_source = "enrichment.post_enrichment_accuracy"

# Loud-failure guard — refuse to start the loop with degenerate inputs.
assert_lever_loop_inputs_sane(
    {"overall_accuracy": baseline["overall_accuracy"], "scores": baseline["scores"]}
)

import mlflow
mlflow.set_experiment(exp_name)
mlflow.openai.autolog()

_banner("Resolved Upstream Task Values")
_log(
    "Inputs",
    run_id=run_id,
    space_id=space_id,
    domain=domain,
    catalog=catalog,
    schema=schema,
    experiment_name=exp_name,
    max_iterations=max_iterations,
    levers=levers,
    apply_mode=apply_mode,
    prev_accuracy=prev_accuracy,
    prev_accuracy_source=_accuracy_source,
    prev_thresholds_met=thresholds_met,
    prev_model_id=prev_model_id,
    baseline_model_id=baseline_model_id,
    enrichment_model_id=enrichment_model_id,
    enrichment_skipped=enrichment_skipped,
    triggered_by=triggered_by,
)
_log(
    "Handoff sources (TASK_VALUES = healthy, DELTA_FALLBACK = repaired)",
    run_id_source=ctx["run_id"].source.value,
    space_id_source=ctx["space_id"].source.value,
    levers_source=ctx["levers"].source.value,
    baseline_accuracy_source=baseline["overall_accuracy"].source.value,
    baseline_scores_source=baseline["scores"].source.value,
    enrichment_skipped_source=enrichment["enrichment_skipped"].source.value,
    enrichment_model_id_source=enrichment["enrichment_model_id"].source.value,
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🚪 Baseline Gate Check
# MAGIC
# MAGIC > **📝 Note:** If `thresholds_met` is `True`, we skip the lever loop and publish baseline values as the final result. Downstream tasks (finalize, deploy) receive the same structure whether we skipped or ran the loop.

# COMMAND ----------

if thresholds_met:
    _banner("Starting Point Gate: SKIP Lever Loop")
    # PR 34: ``prev_scores`` is the resolved current state (baseline OR
    # post-enrichment) — publishing the raw baseline ``scores_json`` here
    # would leak stale values whenever Task 3 produced a fresh
    # post-enrichment evaluation.
    _skip_reason = (
        "post_enrichment_meets_thresholds"
        if _accuracy_source == "enrichment.post_enrichment_accuracy"
        else "baseline_meets_thresholds"
    )
    _log(
        "Skip reason",
        reason=_skip_reason,
        accuracy_source=_accuracy_source,
        accuracy=prev_accuracy,
    )
    effective_model_id = enrichment_model_id if not enrichment_skipped else prev_model_id
    _log("Effective model ID", effective_model_id=effective_model_id, enrichment_model_id=enrichment_model_id, baseline_model_id=prev_model_id)
    dbutils.jobs.taskValues.set(key="scores", value=json.dumps(prev_scores))
    dbutils.jobs.taskValues.set(key="accuracy", value=prev_accuracy)
    dbutils.jobs.taskValues.set(key="model_id", value=effective_model_id)
    dbutils.jobs.taskValues.set(key="iteration_counter", value=0)
    dbutils.jobs.taskValues.set(key="skipped", value=True)
    dbutils.notebook.exit(f"SKIPPED: {_skip_reason} (source={_accuracy_source})")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔄 Loading Benchmarks
# MAGIC
# MAGIC - **Benchmarks:** Loaded from `{catalog}.{schema}.genie_benchmarks_{domain}`.
# MAGIC
# MAGIC > **📝 Note:** Proactive enrichment (descriptions, joins, metadata, instructions, example SQLs) has already been applied by Task 3 (enrichment). The lever loop loads the enriched config directly from the Genie Space API.

# COMMAND ----------

uc_schema = f"{catalog}.{schema}"
_all_benchmarks = load_benchmarks_from_dataset(spark, uc_schema, domain)
benchmarks = [b for b in _all_benchmarks if b.get("split") != "held_out"]
_held_out_n = len(_all_benchmarks) - len(benchmarks)
_banner("Loaded Benchmarks")
_log(
    "Benchmark dataset (train/held-out split)",
    uc_schema=uc_schema,
    domain=domain,
    total_loaded=len(_all_benchmarks),
    train_count=len(benchmarks),
    held_out_count=_held_out_n,
    note="held-out reserved for Finalize generalization check",
)
if not benchmarks:
    raise RuntimeError(f"No benchmarks found in {uc_schema}.genie_benchmarks_{domain}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔧 Adaptive Lever Loop
# MAGIC
# MAGIC The core optimization loop. Each iteration:
# MAGIC 1. Re-cluster failures from the latest evaluation
# MAGIC 2. Rank clusters by `cluster_impact()` (causal weight × severity × fixability)
# MAGIC 3. Call the LLM strategist to propose exactly 1 action group
# MAGIC 4. Apply patches and run 3-gate evaluation (slice → P0 → full)
# MAGIC 5. Accept (if accuracy improves) or rollback (if regression)
# MAGIC 6. Build reflection entry for the next iteration's context
# MAGIC 7. Check convergence (thresholds met, diminishing returns, no clusters left)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Optimization Summary
# MAGIC
# MAGIC After the loop completes, print a comprehensive summary comparing baseline
# MAGIC vs. final accuracy, listing all iterations, and accepted/rolled-back levers.

# COMMAND ----------

try:
    _banner("Running _run_lever_loop (enrichment already done by Task 3)")
    loop_out = _run_lever_loop(
        w, spark, run_id, space_id, domain, benchmarks, exp_name,
        prev_scores, prev_accuracy, prev_model_id, {},
        catalog, schema, levers, max_iterations,
        apply_mode=apply_mode,
        triggered_by=triggered_by,
        human_corrections=human_corrections,
        enrichment_done=True,
        enrichment_model_id=enrichment_model_id,
        max_benchmark_count=max_benchmark_count,
    )
    _log(
        "Lever loop finished",
        accuracy=loop_out["accuracy"],
        iteration_counter=loop_out["iteration_counter"],
        best_iteration=loop_out["best_iteration"],
        levers_attempted=loop_out["levers_attempted"],
        levers_accepted=loop_out["levers_accepted"],
        levers_rolled_back=loop_out["levers_rolled_back"],
    )
except Exception as exc:
    _banner("Lever Loop FAILED")
    _log(
        "Failure details",
        error_type=type(exc).__name__,
        error_message=str(exc),
        traceback=traceback.format_exc(),
    )
    raise

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🪞 GSO Run Pretty-Print
# MAGIC
# MAGIC When Phase H bundle assembly succeeded, the harness returns the rendered process-first transcript via
# MAGIC `loop_out["pretty_print_transcript"]`. Print it once here so it appears in the lever-loop notebook
# MAGIC stdout (recoverable via `databricks jobs export-run --views-to-export ALL`). When the key is absent
# MAGIC (replay path, legacy harness, or bundle assembly failed loudly), this cell is a no-op.

# COMMAND ----------

_pretty_print_transcript = loop_out.get("pretty_print_transcript")
if _pretty_print_transcript:
    print()
    print(_pretty_print_transcript)
    print()
else:
    # Phase-H reliability fix: the harness now stamps precise
    # diagnostics on loop_out so we can distinguish render failures
    # from upload failures from missing anchors from legacy skips.
    # Fall back to ``phase_h_transcript_unavailable`` only when the
    # harness is from a pre-fix build that doesn't emit the reason.
    _log(
        "Pretty-print transcript not available",
        reason=loop_out.get("phase_h_pretty_print_reason", "phase_h_transcript_unavailable"),
        status=loop_out.get("phase_h_pretty_print_status"),
        upload_status=loop_out.get("phase_h_upload_status"),
        anchor_run_id=loop_out.get("phase_h_anchor_run_id"),
    )

# COMMAND ----------

# MAGIC %md
# MAGIC ## 📤 Publishing Task Values
# MAGIC
# MAGIC Task 5 (finalize) and Task 6 (deploy) consume these values. The keys must match what downstream notebooks expect.

# COMMAND ----------

_banner("Publishing Task Values")
dbutils.jobs.taskValues.set(key="scores", value=json.dumps(loop_out["scores"]))
dbutils.jobs.taskValues.set(key="accuracy", value=loop_out["accuracy"])
dbutils.jobs.taskValues.set(key="model_id", value=loop_out["model_id"])
dbutils.jobs.taskValues.set(key="iteration_counter", value=loop_out["iteration_counter"])
dbutils.jobs.taskValues.set(key="best_iteration", value=loop_out["best_iteration"])
dbutils.jobs.taskValues.set(key="skipped", value=False)
dbutils.jobs.taskValues.set(
    key="all_eval_mlflow_run_ids",
    value=json.dumps(loop_out.get("all_eval_mlflow_run_ids", []), default=str),
)
dbutils.jobs.taskValues.set(
    key="all_failure_question_ids",
    value=json.dumps(loop_out.get("all_failure_question_ids", []), default=str),
)

debug_info = {
    k: v for k, v in loop_out.items()
    if k.startswith("_debug_") or k in (
        "levers_attempted",
        "levers_accepted",
        "levers_rolled_back",
        "iteration_counter",
        # Phase B observability manifest. ``loop_out["phase_b"]`` is the
        # CLI-visible truth surface for Phase B because
        # ``databricks jobs get-run-output`` exposes only the
        # ``dbutils.notebook.exit(...)`` JSON for this task — not stdout.
        # Without this allowlist entry the manifest is silently dropped.
        # See `docs/2026-05-02-unified-trace-and-operator-transcript-plan.md`
        # postmortem follow-up.
        "phase_b",
    )
}

# Phase F+H C18 (v2) — Phase H T13: surface the bundle pointers in
# the exit JSON under the contract names defined in
# ``run_analysis_contract.lever_loop_exit_manifest`` (``parent_bundle_run_id``,
# ``artifact_index_path``, ``iterations_completed``). The harness names
# them ``phase_h_*`` internally; we re-key here so postmortem tooling
# reads the same field names whether it consumes ``debug_info`` or a
# future ``lever_loop_exit_manifest(...)`` call.
_phase_h_anchor = loop_out.get("phase_h_anchor_run_id")
if _phase_h_anchor:
    debug_info["parent_bundle_run_id"] = str(_phase_h_anchor)
_phase_h_idx_path = loop_out.get("phase_h_artifact_index_path")
if _phase_h_idx_path:
    debug_info["artifact_index_path"] = str(_phase_h_idx_path)
_phase_h_iters = loop_out.get("phase_h_iterations_completed")
if _phase_h_iters is not None:
    debug_info["iterations_completed"] = [int(n) for n in _phase_h_iters]

# Phase-H reliability fix: include Phase H status diagnostics in the
# exit JSON so ``databricks jobs get-run-output`` can explain what
# happened even when stdout is unavailable. The vocabulary matches
# ``_build_loop_out_with_pretty_print`` / harness termination.
for _phase_h_key in (
    "phase_h_pretty_print_status",
    "phase_h_pretty_print_reason",
    "phase_h_upload_status",
):
    _phase_h_val = loop_out.get(_phase_h_key)
    if _phase_h_val is not None:
        debug_info[_phase_h_key] = str(_phase_h_val)

dbutils.jobs.taskValues.set(key="debug_info", value=json.dumps(debug_info, default=str))

_log(
    "Task values published",
    accuracy=loop_out["accuracy"],
    model_id=loop_out["model_id"],
    iteration_counter=loop_out["iteration_counter"],
    debug_info=debug_info,
)
_banner("Task 4 Completed")
dbutils.notebook.exit(json.dumps(debug_info, default=str))

# COMMAND ----------

# MAGIC %md
# MAGIC ## ✅ What Success Looks Like
# MAGIC
# MAGIC When this task completes successfully (iterations accepted), you will see output similar to:
# MAGIC
# MAGIC ```
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Running _run_lever_loop
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 1
# MAGIC   Clusters: 5 hard failures, 2 soft signals
# MAGIC   Top cluster: wrong_table (impact 12.5, 3 questions)
# MAGIC [TASK-4 LEVER_LOOP] AG applied: 3 patches (Lever 1: 2, Lever 5: 1)
# MAGIC [TASK-4 LEVER_LOOP] Slice gate: PASSED
# MAGIC [TASK-4 LEVER_LOOP] Full eval: PASSED (accuracy 72.5% -> 78.0%)
# MAGIC [TASK-4 LEVER_LOOP] Iteration 1: ACCEPTED
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 2
# MAGIC   Reflection: Iter 1 accepted +5.5%, wrong_table fixed
# MAGIC   Clusters: 3 hard failures remaining
# MAGIC [TASK-4 LEVER_LOOP] AG applied: 2 patches (Lever 5: 2)
# MAGIC [TASK-4 LEVER_LOOP] Slice gate: FAILED (regression -1.2%)
# MAGIC [TASK-4 LEVER_LOOP] Iteration 2: ROLLED BACK
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 3
# MAGIC   Reflection: Iter 2 rolled back, avoid example_sql for ambiguous questions
# MAGIC   Clusters: 3 hard failures remaining
# MAGIC ...
# MAGIC [TASK-4 LEVER_LOOP] OPTIMIZATION RUN SUMMARY
# MAGIC   Baseline accuracy: 72.5%
# MAGIC   Final accuracy: 85.0%
# MAGIC   Iterations: 3 attempted, 2 accepted, 1 rolled back
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Task 4 Completed
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC ```
# MAGIC
# MAGIC When the baseline gate triggers a skip:
# MAGIC
# MAGIC ```
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Baseline Gate: SKIP Lever Loop
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Skip reason
# MAGIC   {"reason": "baseline_meets_thresholds", "baseline_accuracy": 95.2}
# MAGIC ```
# MAGIC
# MAGIC ## 📋 Summary
# MAGIC
# MAGIC Task 4 (Lever Loop) is a **thin wrapper** around `_run_lever_loop()` with `enrichment_done=True`.
# MAGIC Proactive enrichment (descriptions, joins, metadata, instructions, example SQLs) is handled by
# MAGIC Task 3 (enrichment). The lever loop loads the enriched config from the Genie Space API and runs
# MAGIC the adaptive optimization engine: re-clustering failures, scoring by impact, calling the strategist
# MAGIC for 1 action group per iteration, applying patches via 3-gate evaluation (slice → P0 → full),
# MAGIC and reflecting on outcomes to guide future iterations.
# MAGIC
# MAGIC All business logic lives in the harness (`optimization/harness.py`), shared identically by
# MAGIC the DAG notebooks and the `optimize_genie_space()` convenience function.
