"""Stage 5: Proposal Generation (Phase F5).

Wraps the existing ``decision_emitters.proposal_generated_records``
producer in a typed ``ProposalsInput`` / ``ProposalSlate`` surface so
F6 (gates) can read the slate from a stage-aligned dataclass. Also
stamps each accepted proposal with a ``content_fingerprint`` via
``reflection_retry.patch_retry_signature`` (PR-E groundwork — F6 and
F9 read this field for content-fingerprint dedup).

F5 is observability-only: per the plan's Reality Check, the
``generate_proposals_from_strategy`` invocation in harness.py is
preceded by ~50 lines of cluster-driven-synthesis dispatch and lives
inside the per-AG loop. Lifting that under F5's byte-stability gate
is high-risk. F5 stands up the typed surface and PROPOSAL_GENERATED
emission entry; the actual proposal generation stays in harness for
now and is deferred to a follow-up plan.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence

from genie_space_optimizer.optimization.decision_emitters import (
    proposal_generated_records,
)
from genie_space_optimizer.optimization.rca_decision_trace import (
    AlternativeOption,
)
from genie_space_optimizer.optimization.reflection_retry import (
    patch_retry_signature,
)


STAGE_KEY: str = "proposal_generation"


@dataclass
class ProposalsInput:
    """Input to stages.proposals.generate.

    ``proposals_by_ag`` is the slate of proposals already generated by
    the harness's per-AG synthesis dispatch. ``rca_id_by_cluster`` and
    ``cluster_root_cause_by_id`` are needed by
    ``proposal_generated_records`` to populate the rca_id and
    root_cause fields. ``proposal_alternatives_by_ag`` carries Phase D.5
    rejected-alternatives stamping for each AG.
    """

    proposals_by_ag: dict[str, tuple[Mapping[str, Any], ...]]
    rca_id_by_cluster: Mapping[str, str] = field(default_factory=dict)
    cluster_root_cause_by_id: Mapping[str, str] = field(default_factory=dict)
    proposal_alternatives_by_ag: Mapping[str, Sequence[AlternativeOption]] = (
        field(default_factory=dict)
    )


@dataclass
class ProposalSlate:
    """Output of stages.proposals.generate.

    ``proposals_by_ag`` mirrors the input but every proposal is stamped
    with ``content_fingerprint`` (the 6-tuple from
    ``patch_retry_signature`` joined to a string).
    ``rejected_proposal_alternatives`` is the union of any
    alternative-option records the caller passed in.
    ``content_fingerprints_emitted`` is the aggregated tuple of every
    fingerprint stamped — F6's content-fingerprint dedup gate consumes
    this.
    """

    proposals_by_ag: dict[str, tuple[dict[str, Any], ...]]
    rejected_proposal_alternatives: tuple[Mapping[str, Any], ...] = ()
    content_fingerprints_emitted: tuple[str, ...] = ()


def _content_fingerprint(patch: Mapping[str, Any]) -> str:
    """Compute a stable content fingerprint for a patch using
    ``reflection_retry.patch_retry_signature``.

    The signature returns a 6-tuple; we stringify it so the fingerprint
    is a single comparable string. F6's dedup gate uses this exact
    stringified form to compare against rolled-back fingerprints.
    """
    sig = patch_retry_signature(dict(patch))
    parts: list[str] = []
    for s in sig:
        if isinstance(s, frozenset):
            parts.append(",".join(sorted(s)))
        else:
            parts.append(str(s))
    return "|".join(parts)


def generate(ctx, inp: ProposalsInput) -> ProposalSlate:
    """Stage 5 entry. Stamps content_fingerprint on every proposal,
    emits PROPOSAL_GENERATED records, returns a typed slate.

    F5 is observability-only — does NOT invoke the synthesis pipeline.
    Harness still owns the synthesis dispatch and feeds the result
    into ``inp.proposals_by_ag`` when the harness wire-up lands in a
    follow-up plan.
    """
    # Optimizer Control-Plane Hardening Plan — Task D. When the
    # GSO_RCA_AWARE_PATCH_CAP flag is on, stamp ``rca_id`` from the
    # parent cluster onto every proposal that doesn't already carry
    # one, so ``select_causal_patch_cap`` can rank by
    # ``causal_attribution_tier`` instead of insertion order. Default-
    # off preserves legacy (insertion-order) ranking behaviour.
    from genie_space_optimizer.common.config import (
        rca_aware_patch_cap_enabled as _rca_aware_patch_cap_enabled,
    )
    stamp_rca = _rca_aware_patch_cap_enabled()

    fingerprinted: dict[str, tuple[dict[str, Any], ...]] = {}
    fingerprints: list[str] = []

    for ag_id, proposals in (inp.proposals_by_ag or {}).items():
        ag_fingerprinted: list[dict[str, Any]] = []
        for proposal in proposals:
            stamped = dict(proposal)
            if stamp_rca and not stamped.get("rca_id"):
                cluster_id = (
                    str(stamped.get("primary_cluster_id") or "")
                    or next(
                        (
                            str(c)
                            for c in (stamped.get("source_cluster_ids") or ())
                        ),
                        "",
                    )
                )
                if cluster_id:
                    inherited = inp.rca_id_by_cluster.get(cluster_id)
                    if inherited:
                        stamped["rca_id"] = str(inherited)
            fingerprint = _content_fingerprint(proposal)
            stamped["content_fingerprint"] = fingerprint
            ag_fingerprinted.append(stamped)
            fingerprints.append(fingerprint)
        fingerprinted[str(ag_id)] = tuple(ag_fingerprinted)

        records = proposal_generated_records(
            run_id=ctx.run_id,
            iteration=ctx.iteration,
            ag_id=str(ag_id),
            proposals=ag_fingerprinted,
            rca_id_by_cluster=inp.rca_id_by_cluster,
            cluster_root_cause_by_id=inp.cluster_root_cause_by_id,
            proposal_alternatives_for_ag=inp.proposal_alternatives_by_ag.get(
                str(ag_id)
            ),
        )
        for record in records:
            ctx.decision_emit(record)

    return ProposalSlate(
        proposals_by_ag=fingerprinted,
        rejected_proposal_alternatives=(),
        content_fingerprints_emitted=tuple(fingerprints),
    )


# ── Phase H: explicit Input/Output class declarations ─────────────────
# Phase H's per-stage I/O capture decorator imports these to serialize
# the stage's typed input and output to MLflow.
INPUT_CLASS = ProposalsInput
OUTPUT_CLASS = ProposalSlate


# ── G-lite: uniform execute() alias ───────────────────────────────────
# The named verb above is preserved for human-readable harness call
# sites. The ``execute`` alias is what the stage registry, conformance
# test, and Phase H capture decorator import.
execute = generate
