"""DDL constants for GSO optimization Delta tables.

Extracted into a standalone module so that deploy scripts (e.g.
``scripts/grant_permissions.py``) can import ``_ALL_DDL`` without
pulling in pandas or other heavy runtime dependencies.
"""

from genie_space_optimizer.common.config import (
    TABLE_ASI,
    TABLE_FINALIZE_ATTESTATION,
    TABLE_ITERATIONS,
    TABLE_PATCHES,
    TABLE_PROVENANCE,
    TABLE_RUNS,
    TABLE_STAGES,
    TABLE_SUGGESTIONS,
)

# ── Table Names (not in common/config.py) ─────────────────────────────

TABLE_DATA_ACCESS_GRANTS = "genie_opt_data_access_grants"

# Task 1: Ground-truth correction queue.
# When the arbiter rules ``genie_correct`` on a row whose
# ``result_correctness`` is ``no``, the GT itself is wrong or
# under-specified; the row is parked here for human/automated review
# rather than driving the lever loop.
TABLE_GT_CORRECTION_CANDIDATES = "genie_eval_gt_correction_candidates"

# Task 3: Decision audit. Single Delta surface for every gate decision
# (acceptance, proposal grounding, reflection drops, AFS / leakage
# rejections, etc.). Carries source_cluster_ids_json and
# proposal_to_patch_map_json so a single SQL query reconstructs
# cluster -> proposal -> patch -> applied -> accepted/rolled_back.
TABLE_LEVER_LOOP_DECISIONS = "genie_eval_lever_loop_decisions"

# Task 4: Per-question pass/fail transition tracker. Persisted full-eval
# transitions so a bundle that flips a previously-passing qid from pass
# to fail rolls back regardless of aggregate direction.
TABLE_QUESTION_REGRESSIONS = "genie_eval_question_regressions"

# Task 8: Human-required escalation queue. After a cluster's signature
# accumulates ``HUMAN_REQUIRED_CONTENT_ROLLBACK_THRESHOLD`` content
# regressions in the same run, the optimizer stops proposing patches
# for it and parks an evidence record here for human review.
TABLE_HUMAN_REQUIRED = "genie_eval_human_required"

# Task 9: proactive feature-mining artifacts. Persisted per run so a
# reviewer can inspect "what did the proactive miner find on the
# passing corpus, and what enrichments did it propose?" without
# replaying the run.
TABLE_PROACTIVE_CORPUS_PROFILE = "genie_eval_proactive_corpus_profile"
TABLE_PROACTIVE_PATCHES = "genie_eval_proactive_patches"

# ── DDL Constants ────────────────────────────────────────────────────────

_GENIE_OPT_RUNS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_runs (
    run_id              STRING        NOT NULL COMMENT 'UUID for this optimization run',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID being optimized',
    domain              STRING        NOT NULL COMMENT 'Domain name (e.g. revenue_property)',
    catalog             STRING        NOT NULL COMMENT 'Unity Catalog name',
    uc_schema           STRING        NOT NULL COMMENT 'UC schema (catalog.schema format)',
    status              STRING        NOT NULL COMMENT 'QUEUED|IN_PROGRESS|CONVERGED|STALLED|MAX_ITERATIONS|FAILED|CANCELLED',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When the run was created',
    completed_at        TIMESTAMP              COMMENT 'When the run reached a terminal state',
    job_run_id          STRING                 COMMENT 'Databricks Job run ID',
    job_id              STRING                 COMMENT 'Databricks Job definition ID',
    max_iterations      INT           NOT NULL COMMENT 'Maximum lever iterations allowed',
    levers              STRING        NOT NULL COMMENT 'JSON array of lever numbers to try, e.g. [1,2,3,4,5]',
    apply_mode          STRING        NOT NULL COMMENT 'Where patches are applied: genie_config|uc_artifact|both',
    deploy_target       STRING                 COMMENT 'DABs target for post-optimization deploy (null = no deploy)',
    benchmarks_generated BOOLEAN                COMMENT 'True if benchmarks were auto-generated by LLM during this run',
    best_iteration      INT                    COMMENT 'Iteration number with highest accuracy',
    best_accuracy       DOUBLE                 COMMENT 'Best overall accuracy achieved (0-100)',
    best_repeatability  DOUBLE                 COMMENT 'Best repeatability percentage (0-100)',
    best_model_id       STRING                 COMMENT 'MLflow LoggedModel ID for the best iteration',
    convergence_reason  STRING                 COMMENT 'Why the run stopped (threshold_met|plateau|max_iterations|error)',
    experiment_name     STRING                 COMMENT 'MLflow experiment path',
    experiment_id       STRING                 COMMENT 'MLflow experiment ID',
    config_snapshot     STRING                 COMMENT 'JSON: Genie Space config at run start',
    triggered_by        STRING                 COMMENT 'User email who initiated the run',
    labeling_session_name STRING               COMMENT 'MLflow labeling session name for human review',
    labeling_session_run_id STRING             COMMENT 'MLflow run ID associated with the labeling session',
    labeling_session_url STRING                COMMENT 'URL to the MLflow Review App labeling session',
    warehouse_id        STRING                 COMMENT 'SQL warehouse ID resolved at preflight; used by lever_loop / finalize / deploy as a Delta-fallback for the preflight taskValue when Repair Run drops in-memory state',
    human_corrections_json STRING              COMMENT 'JSON array of carry-forward human corrections loaded by preflight; Delta-fallback for the preflight.human_corrections taskValue',
    max_benchmark_count INT                    COMMENT 'Effective max benchmark count computed by preflight (target_benchmark_count adjusted for held-out ratio); Delta-fallback for the preflight.max_benchmark_count taskValue',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (space_id)
COMMENT 'Genie Space optimization runs - one row per optimization attempt'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_STAGES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_stages (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    task_key            STRING                 COMMENT 'Databricks Job task key (preflight, baseline_eval, lever_loop, finalize, deploy)',
    stage               STRING        NOT NULL COMMENT 'Stage name (PREFLIGHT_STARTED, LEVER_2_EVAL_DONE, etc.)',
    status              STRING        NOT NULL COMMENT 'STARTED|COMPLETE|FAILED|SKIPPED|ROLLED_BACK',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When this stage began',
    completed_at        TIMESTAMP              COMMENT 'When this stage ended (null if in progress)',
    duration_seconds    DOUBLE                 COMMENT 'Wall-clock duration of this stage',
    lever               INT                    COMMENT 'Lever number (1-5) if this is a lever stage, null otherwise',
    iteration           INT                    COMMENT 'Evaluation iteration number if applicable',
    detail_json         STRING                 COMMENT 'JSON: stage-specific detail',
    error_message       STRING                 COMMENT 'Error message if status=FAILED'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Optimization stage transitions - ordered timeline of what happened'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_ITERATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_iterations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number (0 = baseline)',
    lever               INT                    COMMENT 'Which lever was applied before this eval (null for baseline)',
    eval_scope          STRING        NOT NULL COMMENT 'full|slice|p0|held_out|enrichment',
    timestamp           TIMESTAMP     NOT NULL COMMENT 'When this evaluation completed',
    mlflow_run_id       STRING                 COMMENT 'MLflow run ID for this evaluation',
    model_id            STRING                 COMMENT 'LoggedModel ID used for this evaluation',
    overall_accuracy    DOUBLE        NOT NULL COMMENT 'Overall accuracy percentage (0-100)',
    total_questions     INT           NOT NULL COMMENT 'Number of benchmark questions evaluated',
    correct_count       INT           NOT NULL COMMENT 'Number of questions that passed all judges',
    scores_json         STRING        NOT NULL COMMENT 'JSON: per-judge scores',
    failures_json       STRING                 COMMENT 'JSON: array of failed question IDs',
    remaining_failures  STRING                 COMMENT 'JSON: array of question IDs still failing',
    arbiter_actions_json STRING                COMMENT 'JSON: array of arbiter verdicts',
    repeatability_pct   DOUBLE                 COMMENT 'Repeatability percentage (0-100) if measured',
    repeatability_json  STRING                 COMMENT 'JSON: per-question repeatability details',
    thresholds_met      BOOLEAN       NOT NULL COMMENT 'True if all quality thresholds passed',
    rows_json           STRING                 COMMENT 'JSON: per-question evaluation detail rows',
    reflection_json     STRING                 COMMENT 'JSON: adaptive loop reflection entry for this iteration',
    evaluated_count     INT                    COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)',
    excluded_count      INT                    COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)',
    quarantined_benchmarks_json STRING         COMMENT 'JSON: array of benchmarks removed by pre-evaluation quarantine ({question_id, reason_code, reason_detail, question})',
    leakage_count_by_type STRING               COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 — persisted leak count grouped by patch_type, measured by post-apply audit',
    firewall_rejection_count_by_type STRING    COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 — firewall rejections during this iteration grouped by patch_type',
    secondary_mining_blocked BIGINT            COMMENT 'Bug #4 — count of times the _resolve_lever5_llm_result secondary mining path was blocked this iteration',
    synthesis_slots_persisted BIGINT           COMMENT 'Bug #4 (Phase 3) — structurally-synthesized example_sqls persisted this iteration',
    arbiter_rejection_count BIGINT             COMMENT 'Bug #4 (Phase 3) — synthesis proposals rejected by the arbiter gate this iteration',
    cluster_fallback_to_instruction_count BIGINT COMMENT 'Bug #4 (Phase 3) — clusters that fell back to instruction-only after synthesis failed repeatedly',
    synthesis_archetype_distribution STRING    COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 (Phase 3) — count of persisted synthesized example_sqls per archetype this iteration',
    rolled_back         BOOLEAN       DEFAULT false COMMENT 'Tier 1.1: true if this iteration was rolled back by the accept/rollback gate. Readers that represent current state must filter this out (see _get_baseline_and_best_accuracy, promote_best_model, load_latest_full_iteration).',
    rolled_back_at      TIMESTAMP              COMMENT 'Tier 1.1: timestamp of rollback',
    rollback_reason     STRING                 COMMENT 'Tier 1.1: human-readable rollback reason (mirrors genie_opt_patches.rollback_reason)',
    both_correct_count  INT                    COMMENT 'Tier 1.7: count of rows with arbiter verdict == both_correct. Used to anchor best_accuracy to both_correct_rate when rc=yes overrides inflate overall_accuracy.',
    both_correct_rate   DOUBLE                 COMMENT 'Tier 1.7: both_correct_count / evaluated_count * 100. Stricter than overall_accuracy (which counts arbiter override rows as correct). Lever loop anchors acceptance to this to avoid ghost-ceiling rejections.'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Evaluation iteration results - scores and failures per eval pass'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
)"""

_GENIE_OPT_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration when this patch was applied',
    lever               INT           NOT NULL COMMENT 'Lever number (1-5)',
    patch_index         INT           NOT NULL COMMENT 'Index within the patch set',
    patch_type          STRING        NOT NULL COMMENT 'Patch type from PATCH_TYPES',
    scope               STRING        NOT NULL COMMENT 'genie_config or uc_artifact or both',
    risk_level          STRING        NOT NULL COMMENT 'low|medium|high',
    target_object       STRING                 COMMENT 'Object being modified (table name, column name, etc.)',
    patch_json          STRING        NOT NULL COMMENT 'JSON: full patch definition',
    command_json        STRING                 COMMENT 'JSON: rendered action command',
    rollback_json       STRING                 COMMENT 'JSON: rollback command',
    applied_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was applied',
    rolled_back         BOOLEAN                COMMENT 'True if this patch was subsequently rolled back',
    rolled_back_at      TIMESTAMP              COMMENT 'When the rollback occurred',
    rollback_reason     STRING                 COMMENT 'Why the patch was rolled back',
    proposal_id         STRING                 COMMENT 'FK to the proposal that generated this patch',
    cluster_id          STRING                 COMMENT 'Failure cluster that motivated this patch',
    provenance_json     STRING                 COMMENT 'JSON: full provenance chain from judge verdicts to this patch'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Patch audit trail - every metadata change applied to Genie Space'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_EVAL_ASI_RESULTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_asi_results (
    run_id              STRING        NOT NULL COMMENT 'Optimization run ID',
    mlflow_run_id       STRING                 COMMENT 'MLflow evaluation run ID (for trace linking)',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question ID',
    judge               STRING        NOT NULL COMMENT 'Judge name',
    value               STRING        NOT NULL COMMENT 'Judge verdict (yes|no|skipped|genie_correct|...)',
    failure_type        STRING                 COMMENT 'From FAILURE_TAXONOMY',
    severity            STRING                 COMMENT 'critical|major|minor|info',
    confidence          DOUBLE                 COMMENT 'Judge confidence (0.0-1.0)',
    blame_set           STRING                 COMMENT 'JSON: array of metadata fields blamed',
    counterfactual_fix  STRING                 COMMENT 'Suggested metadata change to fix the issue',
    wrong_clause        STRING                 COMMENT 'SQL clause that is wrong',
    expected_value      STRING                 COMMENT 'What the correct value should be',
    actual_value        STRING                 COMMENT 'What Genie actually produced',
    missing_metadata    STRING                 COMMENT 'What metadata should exist but does not',
    ambiguity_detected  BOOLEAN                COMMENT 'True if the question is ambiguous',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this ASI row was written'
)
USING DELTA
COMMENT 'Actionable Side Information from evaluation judges'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_DATA_ACCESS_GRANTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_data_access_grants (
    grant_id            STRING        NOT NULL COMMENT 'UUID for this grant record',
    target_catalog      STRING        NOT NULL COMMENT 'Catalog the SP was granted access to',
    target_schema       STRING        NOT NULL COMMENT 'Schema the SP was granted access to',
    granted_by          STRING        NOT NULL COMMENT 'User who performed the grant',
    granted_at          TIMESTAMP     NOT NULL COMMENT 'When the grant was applied',
    revoked_at          TIMESTAMP              COMMENT 'When the grant was revoked (null if active)',
    status              STRING        NOT NULL COMMENT 'active|revoked',
    grant_type          STRING        NOT NULL COMMENT 'read|write — read grants SELECT/EXECUTE, write adds MODIFY'
)
USING DELTA
COMMENT 'Tracks UC privileges granted to the app SP for accessing Genie space assets'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_PROVENANCE_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_provenance (
    run_id              STRING        NOT NULL  COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL  COMMENT 'Lever loop iteration',
    lever               INT           NOT NULL  COMMENT 'Lever number (1-5)',
    question_id         STRING        NOT NULL  COMMENT 'Benchmark question ID',
    signal_type         STRING        NOT NULL  COMMENT 'hard or soft',
    arbiter_verdict     STRING                  COMMENT 'Arbiter verdict for this question',
    judge               STRING        NOT NULL  COMMENT 'Judge that failed',
    judge_verdict       STRING        NOT NULL  COMMENT 'Judge verdict (PASS/FAIL)',
    asi_failure_type_raw STRING                 COMMENT 'Raw failure_type from ASI metadata',
    resolved_root_cause STRING        NOT NULL  COMMENT 'Final root cause after resolution chain',
    resolution_method   STRING        NOT NULL  COMMENT 'asi_metadata or rationale_pattern or sql_diff',
    blame_set           STRING                  COMMENT 'JSON array of blamed objects',
    counterfactual_fix  STRING                  COMMENT 'Suggested fix from judge',
    wrong_clause        STRING                  COMMENT 'SQL clause identified as wrong',
    rationale_snippet   STRING                  COMMENT 'First 500 chars of judge rationale',
    expected_sql        STRING                  COMMENT 'Expected SQL (first 2000 chars)',
    generated_sql       STRING                  COMMENT 'Generated SQL (first 2000 chars)',
    cluster_id          STRING        NOT NULL  COMMENT 'Cluster this question was grouped into',
    proposal_id         STRING                  COMMENT 'Proposal generated from this cluster',
    patch_type          STRING                  COMMENT 'Type of patch applied',
    gate_type           STRING                  COMMENT 'slice or p0 or full',
    gate_result         STRING                  COMMENT 'pass or fail or rollback',
    gate_regression     STRING                  COMMENT 'JSON regression details if gate failed',
    logged_at           TIMESTAMP     NOT NULL  COMMENT 'When this row was written'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'End-to-end provenance: links every patch to originating judge verdicts and gate outcomes'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_FINALIZE_ATTESTATION_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_finalize_attestation_matrix (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    qid                 STRING        NOT NULL COMMENT 'Benchmark question_id',
    iteration_idx       STRING        NOT NULL COMMENT 'Canonical marker: "baseline" | "final" | integer iteration index',
    passed              BOOLEAN                COMMENT 'True if the question passed in this sweep (NULL = quarantined/excluded)',
    is_heldout          BOOLEAN       NOT NULL COMMENT 'True if qid is in the held-out subset (evaluated only at baseline+finalize)',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this row was written'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Bug #4 Phase 4 — per-qid pass/fail matrix from baseline + finalize full-corpus sweeps. Drives the user-visible final_accuracy - baseline_accuracy summary.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_SUGGESTIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_suggestions (
    suggestion_id       STRING        NOT NULL COMMENT 'UUID for this suggestion',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID',
    iteration           INT                    COMMENT 'Lever-loop iteration that produced this suggestion',
    lever               INT                    COMMENT 'Lever number that produced this suggestion',
    type                STRING        NOT NULL COMMENT 'METRIC_VIEW | FUNCTION',
    title               STRING        NOT NULL COMMENT 'Short human-readable title',
    rationale           STRING                 COMMENT 'Why the strategist proposed this',
    definition          STRING                 COMMENT 'SQL or pseudocode definition',
    affected_questions  STRING                 COMMENT 'JSON array of question IDs that would benefit',
    estimated_impact    STRING                 COMMENT 'Estimated accuracy improvement description',
    status              STRING        NOT NULL COMMENT 'PROPOSED | ACCEPTED | REJECTED | IMPLEMENTED',
    reviewed_by         STRING                 COMMENT 'User who reviewed the suggestion',
    reviewed_at         TIMESTAMP              COMMENT 'When the suggestion was reviewed',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the suggestion was created',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Strategist improvement suggestions — proposed metric views and functions for human review'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 3: lever-loop decision audit. ``stage_letter`` follows the
# Pipeline Hand-off Contract (A..O) so a single query joins every
# decision back to its eval pass. ``proposal_to_patch_map_json`` is
# non-null on apply / acceptance rows; the attribution invariant lives
# in ``test_decision_audit.py``.
_GENIE_EVAL_LEVER_LOOP_DECISIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_lever_loop_decisions (
    run_id                       STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration                    INT           NOT NULL COMMENT 'Iteration index',
    ag_id                        STRING                 COMMENT 'Action group id; NULL for pre-AG rows',
    decision_order               INT           NOT NULL COMMENT 'Monotonic order within an AG; ties broken by created_at',
    stage_letter                 STRING                 COMMENT 'Pipeline Hand-off Contract letter (A..O)',
    gate_name                    STRING        NOT NULL COMMENT 'Logical gate name: full_eval_acceptance, post_arbiter_guardrail, asi_extraction, proposal_grounding, ...',
    decision                     STRING        NOT NULL COMMENT 'accepted | rolled_back | dropped | pass | fail | ok | degraded',
    reason_code                  STRING                 COMMENT 'Stable code for the decision (e.g. post_arbiter_guardrail, primary_not_improved_in_every_run)',
    reason_detail                STRING                 COMMENT 'Free-text detail; size-bounded to 2000 chars',
    affected_qids_json           STRING                 COMMENT 'JSON array of question ids the decision affected',
    source_cluster_ids_json      STRING                 COMMENT 'JSON array of cluster ids producing the inputs to this decision',
    proposal_ids_json            STRING                 COMMENT 'JSON array of proposal ids the decision evaluated',
    proposal_to_patch_map_json   STRING                 COMMENT 'JSON object {proposal_id: applied_patch_id}; non-null on apply / acceptance rows',
    metrics_json                 STRING                 COMMENT 'JSON object with typed metrics (deltas, counts, scores)',
    created_at                   TIMESTAMP     NOT NULL COMMENT 'When the decision was emitted'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Lever-loop decision audit trail — every gate decision lands here for queryable attribution'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 4: per-question pass/fail transitions on full eval.
# ``transition`` is one of: hold_pass | hold_fail | pass_to_fail |
# fail_to_pass. ``suppressed`` is True when the qid was in the
# GT-correction queue or quarantined; non-suppressed pass_to_fail
# blocks acceptance.
_GENIE_EVAL_QUESTION_REGRESSIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_question_regressions (
    run_id                       STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration                    INT           NOT NULL COMMENT 'Iteration index',
    ag_id                        STRING        NOT NULL COMMENT 'Action group id',
    question_id                  STRING        NOT NULL COMMENT 'Benchmark question id',
    was_passing                  BOOLEAN                COMMENT 'Pass state on the previous-best eval',
    is_passing                   BOOLEAN                COMMENT 'Pass state on the post-AG eval',
    transition                   STRING                 COMMENT 'hold_pass | hold_fail | pass_to_fail | fail_to_pass',
    pre_arbiter_before           BOOLEAN                COMMENT 'Pre-arbiter pass on previous-best',
    pre_arbiter_after            BOOLEAN                COMMENT 'Pre-arbiter pass post-AG',
    post_arbiter_before          BOOLEAN                COMMENT 'Post-arbiter pass on previous-best',
    post_arbiter_after           BOOLEAN                COMMENT 'Post-arbiter pass post-AG',
    source_cluster_ids_json      STRING                 COMMENT 'Clusters this qid contributed to in the current iteration',
    source_proposal_ids_json     STRING                 COMMENT 'Proposals targeted at those clusters',
    applied_patch_ids_json       STRING                 COMMENT 'Patches applied this iteration',
    suppressed                   BOOLEAN                COMMENT 'True if qid was in GT-correction queue or quarantined',
    created_at                   TIMESTAMP     NOT NULL COMMENT 'When the transition was recorded'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Per-question pass/fail transition tracker — a non-suppressed pass_to_fail rolls back the AG'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 8: human-required escalation queue. Persisted record of the
# cluster signatures the optimizer is giving up on within a run. The
# associated qids are excluded from future strategist input until a
# reviewer either fixes the underlying GT or instruction gap. Each
# row carries the typed evidence (recent rollback reasons,
# attempt_count, root_cause) needed for the reviewer to act on the
# case without scrolling stdout.
_GENIE_EVAL_HUMAN_REQUIRED_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_human_required (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    cluster_signature   STRING        NOT NULL COMMENT 'sha1-derived cluster identity (Task 2.1)',
    question_id         STRING                 COMMENT 'Affected qid (one row per qid)',
    root_cause          STRING                 COMMENT 'Dominant root cause from the cluster',
    attempt_count       INT                    COMMENT 'Distinct content-regression rollbacks observed',
    last_iteration      INT                    COMMENT 'Iteration of the most recent rollback',
    reason_code         STRING                 COMMENT 'persistent_content_rollback | stuck_convergence',
    evidence_json       STRING                 COMMENT 'Compact JSON evidence: rollback reasons, levers tried, score deltas',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the escalation was filed'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Cluster signatures the optimizer escalated to human review within a run (Task 8)'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 9: proactive feature-mining persistence. Two tables —
# ``genie_eval_proactive_corpus_profile`` records the aggregate
# profile per run (what frequencies the miner observed across the
# passing corpus); ``genie_eval_proactive_patches`` records the
# emitted enrichment patches with their ``source_signal`` (what
# observation drove the proposal) and ``frequency`` (how strong the
# evidence was). Together they let a reviewer audit the proactive
# pipeline without replaying the run.
_GENIE_EVAL_PROACTIVE_CORPUS_PROFILE_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_proactive_corpus_profile (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration index where the profile was computed (typically 0)',
    table_id            STRING                 COMMENT 'Asset id the profile is scoped to',
    profile_blob        STRING                 COMMENT 'JSON-serialized CorpusProfile counters',
    eligible_row_count  INT                    COMMENT 'Passing rows that contributed to the profile',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the profile was persisted'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Aggregate corpus feature profiles from Task 9 proactive mining'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_EVAL_PROACTIVE_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_proactive_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration index where the patch was generated',
    patch_id            STRING        NOT NULL COMMENT 'Stable id within (run_id, iteration)',
    patch_type          STRING                 COMMENT 'update_column_description | add_join_spec | add_sql_snippet_expression | ...',
    target              STRING                 COMMENT 'Table.column or join target',
    table_id            STRING                 COMMENT 'Asset id the patch enriches',
    source_signal       STRING                 COMMENT 'What observation drove the proposal (e.g. co_occurs_with:dim, frequent_tvf)',
    frequency           INT                    COMMENT 'Observed frequency of the source signal',
    dedup_route         STRING                 COMMENT 'metric_view_measure_enrich when the candidate was rewritten by the dedup contract',
    dedup_dropped_reason STRING                COMMENT 'Reason code when the dedup contract dropped the candidate',
    applied             BOOLEAN                COMMENT 'True when the patch was applied to the space',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was generated'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Enrichment patches emitted by Task 9 proactive mining (one row per candidate)'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 1: ground-truth correction queue. ``status`` is the four-state
# review machine documented in ``ground_truth_corrections``:
#   pending_review        — initial; reviewer has not looked.
#   accepted_corpus_fix   — GT was updated; qid eligible for proactive
#                           mining (Task 9 reads this status).
#   rejected_keep_gt      — reviewer disagreed; treat as confirmed Genie
#                           failure on next iteration.
#   superseded            — replaced by a later iteration's row.
_GENIE_EVAL_GT_CORRECTION_CANDIDATES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_gt_correction_candidates (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration that produced this candidate',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question id',
    question            STRING                 COMMENT 'Question text (frozen at capture time)',
    expected_sql        STRING                 COMMENT 'Ground-truth SQL believed wrong by the arbiter',
    genie_sql           STRING                 COMMENT 'Genie-produced SQL the arbiter ruled correct',
    arbiter_verdict     STRING                 COMMENT 'Arbiter verdict; expected genie_correct',
    arbiter_rationale   STRING                 COMMENT 'Arbiter explanation for the genie_correct verdict',
    status              STRING        NOT NULL COMMENT 'pending_review | accepted_corpus_fix | rejected_keep_gt | superseded',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the candidate was queued'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Corpus-review queue for benchmark rows where the arbiter ruled Genie correct against a defective GT'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# ── Combined DDL dict ────────────────────────────────────────────────────

_ALL_DDL: dict[str, str] = {
    TABLE_RUNS: _GENIE_OPT_RUNS_DDL,
    TABLE_STAGES: _GENIE_OPT_STAGES_DDL,
    TABLE_ITERATIONS: _GENIE_OPT_ITERATIONS_DDL,
    TABLE_PATCHES: _GENIE_OPT_PATCHES_DDL,
    TABLE_ASI: _GENIE_EVAL_ASI_RESULTS_DDL,
    TABLE_DATA_ACCESS_GRANTS: _GENIE_OPT_DATA_ACCESS_GRANTS_DDL,
    TABLE_PROVENANCE: _GENIE_OPT_PROVENANCE_DDL,
    TABLE_SUGGESTIONS: _GENIE_OPT_SUGGESTIONS_DDL,
    TABLE_FINALIZE_ATTESTATION: _GENIE_OPT_FINALIZE_ATTESTATION_DDL,
    TABLE_GT_CORRECTION_CANDIDATES: _GENIE_EVAL_GT_CORRECTION_CANDIDATES_DDL,
    TABLE_LEVER_LOOP_DECISIONS: _GENIE_EVAL_LEVER_LOOP_DECISIONS_DDL,
    TABLE_QUESTION_REGRESSIONS: _GENIE_EVAL_QUESTION_REGRESSIONS_DDL,
    TABLE_HUMAN_REQUIRED: _GENIE_EVAL_HUMAN_REQUIRED_DDL,
    TABLE_PROACTIVE_CORPUS_PROFILE: _GENIE_EVAL_PROACTIVE_CORPUS_PROFILE_DDL,
    TABLE_PROACTIVE_PATCHES: _GENIE_EVAL_PROACTIVE_PATCHES_DDL,
}
